/**
 * Every string the screen can show, in both interface languages.
 *
 * Kept out of App.tsx so that file stays about layout. Official warning and rule
 * text never appears here — that comes from the domain package verbatim.
 */
export const UI_COPY = Object.freeze({
  zh: Object.freeze({
    themeLightButton: "主題：明亮（切換至暗黑）",
    themeDarkButton: "主題：暗黑（切換至明亮）",
    languageControlLabel: "介面語言",
    languageChinese: "中文",
    languageEnglish: "English",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "健保降血脂藥品查詢",
    appTagline: "查 2026-09-01 新制調整了哪些降血脂品項、每個品項在指定日期的支付價是多少。價格全部取自健保署公開資料。",
    versionPill: "公告生效日 民國115年9月1日 · 藥品主檔 2026-08-06 快照",
    disclaimer:
      "本工具非健保署系統,查詢結果不可作為申報依據,實際品項與價格以健保署公告為準。不判斷任何病人是否符合給付,也不接受病人資料。",
    queryPanelTitle: "查詢條件",
    resultsEmptyTitle: "等待查詢",
    resultsEmptyBody: "輸入健保代碼、中文品名、英文品名或成分,下方會列出品項、該日期適用的支付價,以及是否受 2026-09-01 公告影響。",
    statMatched: "命中品項",
    statPriceChanged: "本次調價",
    statPriceUnchanged: "本次未調價",
    statAsOfDate: "查詢日期",
    advancedTitle: "進階：指定資料集版本",
    showItemDetails: "展開完整欄位",
    officialSourcesTitle: "官方轉錄警語與資料來源",
    sourceMasterLabel: "藥品主檔",
    sourceAnnouncementLabel: "2026-09-01 公告異動明細",
    datasetPlaceholder: "資料集版本",
    filterAll: "全部",
    filterPriceChanged: "本次調價",
    filterPriceUnchanged: "本次未調價",
    doseFilter: "劑量",
    doseFilterAll: "全部劑量（{count}）",
    doseFilterOption: "{label}（{count}）",
    doseUnspecified: "劑量未標示",
    doseNote:
      "劑量取自主檔的成分欄與英文品名兩者聯集。鹽類成分記載的是鹽重（如 atorvastatin calcium 10.85 mg），與標示含量（10 mg）並列，兩個都查得到；數值一律照主檔原樣，不換算、不四捨五入。",
    doseSelectedEmpty: "目前條件下沒有此劑量的品項。",
    announcementChangedTitle: "2026-09-01 公告價格對照",
    priceBefore: "原支付價：{value}",
    priceAfter: "初核價格：{value}",
    effectiveDate: "生效日：{value}",
    missingField: "本資料列未提供",
    fieldIngredient: "成分及含量：{value}",
    fieldSpecification: "規格：{value}",
    fieldVendor: "藥商：{value}",
    fieldManufacturer: "製造廠：{value}",
    fieldAtc: "ATC：{value}",
    fieldCategory: "藥品分類：{value}",
    fieldClassificationGroup: "分類分組名稱：{value}",
    fieldSingleCompound: "單複方：{value}",
    applicablePriceTitle: "該查詢日期適用之支付價",
    masterSnapshotNotice:
      "主檔資料集版本 {version} 為 {snapshotDate} 時點快照；主檔最新價格期間為 {start} 至 {end}。上方公告價格對照另載該快照日之後、生效日 {effectiveDate} 的異動。",
    priceHistoryTitle: "價格沿革",
    validPeriodHeader: "有效期間",
    paymentPriceHeader: "支付價",
    dateRange: "{start} 至 {end}",
    ruleSectionTitle: "給付規定章節",
    drugSearchLabel: "藥品主檔搜尋",
    drugSearchPlaceholder: "輸入中文品名、健保代碼、英文品名或成分",
    drugDateLabel: "藥品主檔查詢日期",
    drugDatasetLabel: "藥品主檔資料集版本",
    drugSearchButton: "查詢藥品主檔",
    resultFilter: "結果篩選",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "查詢結果：{status}",
    multipleReviewDrug:
      "目前畫面列出全部 {count} 筆符合目前條件的候選；工具不會代為選取任何品項或期別。",
    manualReviewDrug: "此結果需要人工確認；系統不會自動選取品項或替代期別。",
    excludedZeroPrice: "另有 {count} 筆符合查詢的品項，因該查詢日期之支付價為 0.00 未列出。",
    asOfDatePresetToday: "今天（{value}）",
    asOfDatePresetAnnouncement: "新制生效日（{value}）",
    asOfDatePickerHint: "點日期欄位可開啟日曆選擇其他日期。價格依所選日期適用之期別顯示。",
    noValidatedItems: "該查詢日期沒有已驗證資料所涵蓋的品項期別。",
    noFilteredItems: "此結果篩選目前沒有品項。",
    statusExact: "單筆精確命中",
    statusMultiple: "多筆命中",
    statusUnavailable: "未在已驗證資料集取得結果",
    privacyText: "請勿輸入姓名、病歷號、檢驗值、診斷或任何可識別病人資訊。",
    footerAttribution:
      "資料來源:衛生福利部中央健康保險署『健保用藥品項查詢項目檔』(政府資料開放平臺),依政府資料開放授權條款第1版利用",
    footerPrivacy: "本站不設帳號、不蒐集任何個人資料;查詢內容不記錄、不儲存。"
  }),
  en: Object.freeze({
    themeLightButton: "Theme: Light (switch to Dark)",
    themeDarkButton: "Theme: Dark (switch to Light)",
    languageControlLabel: "Interface language",
    languageChinese: "中文",
    languageEnglish: "English",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "NHI Lipid-Lowering Drug Lookup",
    appTagline:
      "Which lipid-lowering items the 2026-09-01 announcement repriced, and what each costs on the date you choose. Every price comes from NHI's own published data.",
    versionPill: "Announcement effective 2026-09-01 · Drug master snapshot 2026-08-06",
    disclaimer:
      "This is not an NHI system. Results cannot be used as a basis for claims; the NHI's own announcements govern. The tool makes no coverage determination for any patient and accepts no patient data.",
    queryPanelTitle: "Query",
    resultsEmptyTitle: "Waiting for a query",
    resultsEmptyBody:
      "Enter an NHI code, Chinese or English drug name, or ingredient. Results list each item, the payment price for the date you chose, and whether the 2026-09-01 announcement affected it.",
    statMatched: "Items matched",
    statPriceChanged: "Price changed",
    statPriceUnchanged: "Price not changed",
    statAsOfDate: "Lookup date",
    advancedTitle: "Advanced: pin a dataset version",
    showItemDetails: "Show all fields",
    officialSourcesTitle: "Official transcription warnings and sources",
    sourceMasterLabel: "Drug master",
    sourceAnnouncementLabel: "2026-09-01 announcement change details",
    datasetPlaceholder: "Dataset version",
    filterAll: "All",
    filterPriceChanged: "Price changed",
    filterPriceUnchanged: "Price not changed",
    doseFilter: "Dose",
    doseFilterAll: "All doses ({count})",
    doseFilterOption: "{label} ({count})",
    doseUnspecified: "Dose not stated",
    doseNote:
      "Doses are read from the master's ingredient field and English drug name, unioned. Salt forms state the salt weight (e.g. atorvastatin calcium 10.85 mg) alongside the label strength (10 mg), and both can be searched; values are shown exactly as the master states them, never converted or rounded.",
    doseSelectedEmpty: "No item carries this dose under the current filters.",
    announcementChangedTitle: "2026-09-01 announcement price comparison",
    priceBefore: "Previous payment price: {value}",
    priceAfter: "Initial review price: {value}",
    effectiveDate: "Effective date: {value}",
    missingField: "Not provided in this source row",
    fieldIngredient: "Ingredient and strength: {value}",
    fieldSpecification: "Specification: {value}",
    fieldVendor: "Vendor: {value}",
    fieldManufacturer: "Manufacturer: {value}",
    fieldAtc: "ATC: {value}",
    fieldCategory: "Drug category: {value}",
    fieldClassificationGroup: "Classification group: {value}",
    fieldSingleCompound: "Single or combination product: {value}",
    applicablePriceTitle: "Payment price for the lookup date",
    masterSnapshotNotice:
      "Master dataset version {version} is a snapshot dated {snapshotDate}. Its latest price period runs from {start} to {end}. The announcement price comparison above separately records a change after that snapshot date, effective {effectiveDate}.",
    priceHistoryTitle: "Price history",
    validPeriodHeader: "Effective period",
    paymentPriceHeader: "Payment price",
    dateRange: "{start} to {end}",
    ruleSectionTitle: "Rule section",
    drugSearchLabel: "Drug master search",
    drugSearchPlaceholder: "Enter a Chinese name, NHI code, English name, or ingredient",
    drugDateLabel: "Drug master lookup date",
    drugDatasetLabel: "Drug master dataset version",
    drugSearchButton: "Search drug master",
    resultFilter: "Result filters",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "Lookup result: {status}",
    multipleReviewDrug:
      "The current view lists all {count} candidates matching the current filters; the tool does not select any item or price period for you.",
    manualReviewDrug: "This result requires manual review; no item or price period is selected automatically.",
    excludedZeroPrice:
      "A further {count} item(s) matched the query but are not listed, because their payment price for that date is 0.00.",
    asOfDatePresetToday: "Today ({value})",
    asOfDatePresetAnnouncement: "Announcement effective date ({value})",
    asOfDatePickerHint:
      "Tap the date field to open a calendar and pick another date. Prices are shown for the period covering the date you choose.",
    noValidatedItems: "No item period was found in the verified data for this lookup date.",
    noFilteredItems: "No items match the current factual filter.",
    statusExact: "One exact record match",
    statusMultiple: "Multiple record matches",
    statusUnavailable: "No result in the verified dataset",
    privacyText:
      "Do not enter names, medical record numbers, test results, diagnoses, or any identifiable patient information.",
    footerAttribution:
      "Source: National Health Insurance Administration, Ministry of Health and Welfare, NHI Drug Item Query File (data.gov.tw), used under the Open Government Data License, Version 1.0.",
    footerPrivacy:
      "This site has no accounts and collects no personal data; lookup content is neither logged nor stored."
  })
});

export type UiMessageKey = keyof (typeof UI_COPY)["zh"];
export type UiReplacements = Readonly<Record<string, string>>;
export type Translator = (key: UiMessageKey, replacements?: UiReplacements) => string;
