/**
 * Every string the screen can show, in both interface languages.
 *
 * Kept out of App.tsx so that file stays about layout. Official warning and rule
 * text never appears here — that comes from the domain package verbatim.
 */
export const UI_COPY = Object.freeze({
  zh: Object.freeze({
    skipToContent: "跳到主要內容",
    htmlLang: "zh-Hant",
    documentTitle: "健保降血脂藥品查詢｜風險分級",
    themeLightButton: "主題：明亮（切換至暗黑）",
    themeDarkButton: "主題：暗黑（切換至明亮）",
    languageControlLabel: "介面語言",
    languageChinese: "中文",
    languageEnglish: "English",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "健保降血脂藥品查詢",
    appTagline: "查 2026-09-01 新制調整了哪些降血脂品項、每個品項在指定日期的支付價是多少。價格全部取自健保署公開資料。",
    versionPill: "公告生效日 民國115年9月1日 · 藥品主檔 2026-08-06 快照",
    disclaimer:
      "本工具非健保署系統,查詢結果不可作為申報依據,實際品項、價格與給付規定以健保署公告為準。不判斷任何病人是否符合給付;風險分級依公告附件二的判定條件計算,不構成診斷。不接受姓名、病歷號等可識別病人資料,輸入的數值只留在瀏覽器,重新整理即消失。",
    queryPanelTitle: "查詢條件",
    resultsEmptyTitle: "等待查詢",
    resultsEmptyBody: "輸入健保代碼、中文品名、英文品名或成分,下方會列出品項、該日期適用的支付價,以及是否受 2026-09-01 公告影響。",
    drugResultAnnouncement: "查詢完成。{date} 命中 {count} 個品項,其中 {changed} 個本次調價。結果列在下方。",
    riskAnnouncementDetermined: "已判定為{tier}。該等級的給付門檻、治療目標值與處方規定列在下方。",
    riskAnnouncementUndetermined: "尚無法判定,還有 {count} 題未回答。",
    beyondSnapshotNotice: "查詢日期 {date} 在藥品主檔快照日 {snapshot} 之後。主檔最後一段價格期間是開放式的,所以這個日期仍會回傳快照當時的最後一個價格——那是主檔記到的最後一筆,不是對該日期的保證。快照日之後公告的異動不在主檔中。",
    statMatched: "命中品項",
    statPriceChanged: "本次調價",
    statPriceUnchanged: "本次未調價",
    statAsOfDate: "查詢日期",
    advancedTitle: "進階：指定資料集版本",
    showItemDetails: "展開完整欄位",
    officialSourcesTitle: "官方轉錄警語與資料來源",
    sourceMasterLabel: "藥品主檔",
    sourceAnnouncementLabel: "2026-09-01 公告異動明細",
    datasetPlaceholder: "資料集版本",
    filterAll: "全部",
    filterPriceChanged: "本次調價",
    filterPriceUnchanged: "本次未調價",
    doseFilter: "劑量",
    doseFilterAll: "全部劑量（{count}）",
    doseFilterOption: "{label}（{count}）",
    doseUnspecified: "劑量未標示",
    doseNote:
      "劑量取自主檔的成分欄與英文品名兩者聯集。鹽類成分記載的是鹽重（如 atorvastatin calcium 10.85 mg），與標示含量（10 mg）並列，兩個都查得到；數值一律照主檔原樣，不換算、不四捨五入。",
    doseSelectedEmpty: "目前條件下沒有此劑量的品項。",
    announcementChangedTitle: "2026-09-01 公告價格對照",
    priceBefore: "原支付價：{value}",
    priceAfter: "初核價格：{value}",
    effectiveDate: "生效日：{value}",
    missingField: "本資料列未提供",
    fieldIngredient: "成分及含量：{value}",
    fieldSpecification: "規格：{value}",
    fieldVendor: "藥商：{value}",
    fieldManufacturer: "製造廠：{value}",
    fieldAtc: "ATC：{value}",
    fieldCategory: "藥品分類：{value}",
    fieldClassificationGroup: "分類分組名稱：{value}",
    fieldSingleCompound: "單複方：{value}",
    applicablePriceTitle: "該查詢日期適用之支付價",
    masterSnapshotNotice:
      "主檔資料集版本 {version} 為 {snapshotDate} 時點快照；主檔最新價格期間為 {start} 至 {end}。上方公告價格對照另載該快照日之後、生效日 {effectiveDate} 的異動。",
    priceHistoryTitle: "價格沿革",
    validPeriodHeader: "有效期間",
    paymentPriceHeader: "支付價",
    dateRange: "{start} 至 {end}",
    ruleSectionTitle: "給付規定章節",
    drugSearchLabel: "藥品主檔搜尋",
    drugSearchPlaceholder: "例如：atorvastatin 40mg 這次調價的",
    smartQueryHint: "可以把劑量、要不要調價、日期一起打進來,系統會自動拆開。不認得的字一律當成品名或成分繼續搜尋。",
    smartQueryUnderstood: "已從輸入辨識：",
    smartQueryFacetDose: "劑量 {value}",
    smartQueryFacetPriceChanged: "只看本次調價",
    smartQueryFacetPriceUnchanged: "只看本次未調價",
    smartQueryFacetDate: "查詢日期 {value}",
    smartQueryFacetIgnored: "略過 {value}",
    smartQueryFacetFrom: "（來自「{raw}」）",
    smartQuerySearchedFor: "實際以「{value}」搜尋品名與成分。",
    smartQueryNoText: "請至少輸入一個品名、成分或健保代碼;條件字詞本身不會單獨查詢。",
    drugDateLabel: "藥品主檔查詢日期",
    drugDatasetLabel: "藥品主檔資料集版本",
    drugSearchButton: "查詢藥品主檔",
    resultFilter: "結果篩選",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "查詢結果：{status}",
    multipleReviewDrug:
      "目前畫面列出全部 {count} 筆符合目前條件的候選；工具不會代為選取任何品項或期別。",
    manualReviewDrug: "此結果需要人工確認；系統不會自動選取品項或替代期別。",
    excludedZeroPrice: "另有 {count} 筆符合查詢的品項，因該查詢日期之支付價為 0.00 未列出。",
    asOfDatePresetToday: "今天（{value}）",
    asOfDatePresetAnnouncement: "新制生效日（{value}）",
    asOfDatePickerHint: "點日期欄位可開啟日曆選擇其他日期。價格依所選日期適用之期別顯示。",
    noValidatedItems: "該查詢日期沒有已驗證資料所涵蓋的品項期別。",
    noFilteredItems: "此結果篩選目前沒有品項。",
    statusExact: "單筆精確命中",
    statusMultiple: "多筆命中",
    statusUnavailable: "未在已驗證資料集取得結果",
    showMoreItems: "顯示更多（目前顯示 {shown} / {total} 筆）",
    showingAll: "已顯示全部 {total} 筆。",
    tabDrugLookup: "藥品查詢",
    tabRiskTier: "風險分級",
    tabGroupLabel: "查詢模式",
    riskPanelTitle: "逐題輸入",
    riskRemaining: "尚未回答 {count} 題",
    riskLdlLabel: "目前 LDL-C（mg/dL）",
    riskLdlPlaceholder: "例如 145",
    riskLdlInvalid: "請輸入 0 到 1000 之間的數字。",
    riskLdlWhy: "LDL-C 除了比對給付門檻,本身也是高風險的判定條件之一（LDL-C≧190mg/dL）,所以沒填就無法排除高風險。",
    riskEdit: "修改",
    riskReset: "全部重來",
    riskNext: "下一題",
    riskYes: "是",
    riskNo: "否",
    riskAnsweredYes: "是",
    riskAnsweredNo: "否",
    riskAnyOfHint: "可複選。沒有的就不要勾,按「下一題」即視為皆無。",
    riskPrerequisiteQuestion: "病人有沒有下列情形?",
    riskUndeterminedTitle: "尚無法判定",
    riskUndeterminedBody: "就目前的回答,可能是:{tiers}。尚有 {count} 題未答,其中一部分答完就可能定案,不必全部答完。",
    riskUndeterminedWhy: "沒有回答的題目一律當成「未知」,不會當成「否」——當成否會低估風險等級。",
    riskNeedLdl: "還需要填上方的 LDL-C 才能判定。",
    riskTierEyebrow: "ASCVD 風險等級",
    riskReasonCriterion: "依據:{text}",
    riskReasonWithPrerequisite: "依據:{prerequisite},合併「{text}」",
    riskReasonFactorCount: "依據:{rule}（符合 {count} 項）",
    riskStatLdl: "目前 LDL-C",
    riskStatThreshold: "給付起始門檻",
    riskStatPrimary: "主要目標值",
    riskStatSecondary: "次要目標（non-HDL-C）",
    riskStatBlank: "未填",
    riskStatNone: "公告未列",
    riskPrescriptionTitle: "該等級的處方規定",
    riskPrescriptionNote: "以下每一步都是公告原文,依原文自己的編號分開顯示,未經改寫。",
    riskPrescriptionVerbatim: "官方原文（整段未分段）",
    riskPrescriptionNone: "公告的處方規定欄沒有列出這一列。工具不代為套用其他等級的規定。",
    riskProvenance: "依據:2026-09-01 公告附件二「藥品給付規定修訂對照表」· {version}",
    riskSkipped: "以下題目已不影響結果,自動略過:{reason}",
    riskSkippedTier: "已可判定為{tier}",
    riskNoDrugAdvice: "工具不判讀強度分類,也不代為選取任何品項。用藥選擇請自行判斷。",
    riskAnswersLabel: "已回答",
    riskEmptyTitle: "尚未開始",
    riskEmptyBody: "左欄逐題回答公告附件二的判定條件,右欄會列出算出的風險等級、該等級的給付起始門檻與治療目標值,以及公告原文的處方規定。",
    riskItemsTitle: "對應的健保品項與價格",
    riskItemsNote: "下列是主檔中成分含「{generic}」、於 {date} 有支付價的品項。",
    riskItemsPartial: "公告的處方規定另外提到 {classes}。主檔沒有這幾類的任何品項,所以這裡只涵蓋其中的 statin 與 ezetimibe。",
    riskItemsExcluded: "另有 {count} 筆該日支付價為 0.00,未列入。",
    riskClassStatin: "statin 類（{count}）",
    riskClassEzetimibe: "ezetimibe 類（{count}）",
    riskGenericPrompt: "選一個成分,下方列出該成分的品項與價格。",
    riskGenericChip: "{name}（{count}）",
    riskItemsPickGeneric: "尚未選擇成分。",
    riskAdviceTitle: "該等級的評估建議",
    riskAdviceNote: "公告在表一之後另外列出各風險等級的評估建議。以下是原文,依原文自己的編號分開顯示,未經改寫。",
    riskAdviceNone: "公告的評估建議只分成兩組,沒有寫給這一列。工具不代為套用其他等級的建議。",
    riskSecondaryNoteLabel: "公告對次要目標的說明（原文）",
    riskCoverageTitle: "Ezetimibe 的給付規定",
    riskCoverageNote: "同一份公告也修訂了 ezetimibe 與其複方製劑的給付規定。以下是修訂後的原文,未經改寫;工具不判斷任何病人是否符合,也不與舊版對照。",
    riskCoverageExceptionSummary: "條文中「下表所列項目」的品項",
    riskCoverageExceptionNote: "公告的表列共 {total} 個健保代碼,其中於 {date} 有支付價的 {count} 項如下。",
    riskCoverageUnresolved: "另有 {count} 個代碼在主檔於該日期查無支付價,未列出:{codes}",
    privacyText: "請勿輸入姓名、病歷號或任何可識別病人資訊。臨床數值不記錄、不儲存、不送出。",
    footerAttribution:
      "資料來源:衛生福利部中央健康保險署『健保用藥品項查詢項目檔』(政府資料開放平臺),依政府資料開放授權條款第1版利用",
    footerPrivacy: "本站不設帳號、不蒐集任何個人資料;查詢內容不記錄、不儲存。",
    footerCredit: "本系統之計畫、開發與製作:天義企業 Josh Tsai。"
  }),
  en: Object.freeze({
    skipToContent: "Skip to main content",
    htmlLang: "en",
    documentTitle: "NHI lipid-lowering drug lookup | Risk tier",
    themeLightButton: "Theme: Light (switch to Dark)",
    themeDarkButton: "Theme: Dark (switch to Light)",
    languageControlLabel: "Interface language",
    languageChinese: "中文",
    languageEnglish: "English",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "NHI Lipid-Lowering Drug Lookup",
    appTagline:
      "Which lipid-lowering items the 2026-09-01 announcement repriced, and what each costs on the date you choose. Every price comes from NHI's own published data.",
    versionPill: "Announcement effective 2026-09-01 · Drug master snapshot 2026-08-06",
    disclaimer:
      "This is not an NHI system. Results cannot be used as a basis for claims; the NHI's own announcements govern on items, prices and payment rules. The tool makes no coverage determination for any patient; the risk tier is computed from the announcement's own criteria and is not a diagnosis. It accepts no identifying patient data such as names or record numbers, and values you enter stay in the browser and are gone on reload.",
    queryPanelTitle: "Query",
    resultsEmptyTitle: "Waiting for a query",
    resultsEmptyBody:
      "Enter an NHI code, Chinese or English drug name, or ingredient. Results list each item, the payment price for the date you chose, and whether the 2026-09-01 announcement affected it.",
    drugResultAnnouncement: "Search complete. {count} items match on {date}; {changed} of them were repriced. The results follow below.",
    riskAnnouncementDetermined: "Tier determined: {tier}. Its payment threshold, treatment targets and prescribing rule follow below.",
    riskAnnouncementUndetermined: "Not determined yet. {count} questions are still unanswered.",
    beyondSnapshotNotice: "The lookup date {date} is later than the master snapshot dated {snapshot}. The master\u2019s final price period is open-ended, so this date still returns the last price the snapshot recorded — that is the last entry it holds, not a statement about this date. Anything published after the snapshot is not in it.",
    statMatched: "Items matched",
    statPriceChanged: "Price changed",
    statPriceUnchanged: "Price not changed",
    statAsOfDate: "Lookup date",
    advancedTitle: "Advanced: pin a dataset version",
    showItemDetails: "Show all fields",
    officialSourcesTitle: "Official transcription warnings and sources",
    sourceMasterLabel: "Drug master",
    sourceAnnouncementLabel: "2026-09-01 announcement change details",
    datasetPlaceholder: "Dataset version",
    filterAll: "All",
    filterPriceChanged: "Price changed",
    filterPriceUnchanged: "Price not changed",
    doseFilter: "Dose",
    doseFilterAll: "All doses ({count})",
    doseFilterOption: "{label} ({count})",
    doseUnspecified: "Dose not stated",
    doseNote:
      "Doses are read from the master's ingredient field and English drug name, unioned. Salt forms state the salt weight (e.g. atorvastatin calcium 10.85 mg) alongside the label strength (10 mg), and both can be searched; values are shown exactly as the master states them, never converted or rounded.",
    doseSelectedEmpty: "No item carries this dose under the current filters.",
    announcementChangedTitle: "2026-09-01 announcement price comparison",
    priceBefore: "Previous payment price: {value}",
    priceAfter: "Initial review price: {value}",
    effectiveDate: "Effective date: {value}",
    missingField: "Not provided in this source row",
    fieldIngredient: "Ingredient and strength: {value}",
    fieldSpecification: "Specification: {value}",
    fieldVendor: "Vendor: {value}",
    fieldManufacturer: "Manufacturer: {value}",
    fieldAtc: "ATC: {value}",
    fieldCategory: "Drug category: {value}",
    fieldClassificationGroup: "Classification group: {value}",
    fieldSingleCompound: "Single or combination product: {value}",
    applicablePriceTitle: "Payment price for the lookup date",
    masterSnapshotNotice:
      "Master dataset version {version} is a snapshot dated {snapshotDate}. Its latest price period runs from {start} to {end}. The announcement price comparison above separately records a change after that snapshot date, effective {effectiveDate}.",
    priceHistoryTitle: "Price history",
    validPeriodHeader: "Effective period",
    paymentPriceHeader: "Payment price",
    dateRange: "{start} to {end}",
    ruleSectionTitle: "Rule section",
    drugSearchLabel: "Drug master search",
    drugSearchPlaceholder: "e.g. atorvastatin 40mg repriced",
    smartQueryHint: "Type the strength, whether the price changed, and a date on the same line; they are split out automatically. Anything not recognized is still searched as a name or ingredient.",
    smartQueryUnderstood: "Read from your input: ",
    smartQueryFacetDose: "Dose {value}",
    smartQueryFacetPriceChanged: "Repriced only",
    smartQueryFacetPriceUnchanged: "Not repriced only",
    smartQueryFacetDate: "Lookup date {value}",
    smartQueryFacetIgnored: "Set aside: {value}",
    smartQueryFacetFrom: "(from “{raw}”)",
    smartQuerySearchedFor: "Searched names and ingredients for “{value}”.",
    smartQueryNoText: "Enter at least one name, ingredient or NHI code — a condition word on its own is not searched.",
    drugDateLabel: "Drug master lookup date",
    drugDatasetLabel: "Drug master dataset version",
    drugSearchButton: "Search drug master",
    resultFilter: "Result filters",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "Lookup result: {status}",
    multipleReviewDrug:
      "The current view lists all {count} candidates matching the current filters; the tool does not select any item or price period for you.",
    manualReviewDrug: "This result requires manual review; no item or price period is selected automatically.",
    excludedZeroPrice:
      "A further {count} item(s) matched the query but are not listed, because their payment price for that date is 0.00.",
    asOfDatePresetToday: "Today ({value})",
    asOfDatePresetAnnouncement: "Announcement effective date ({value})",
    asOfDatePickerHint:
      "Tap the date field to open a calendar and pick another date. Prices are shown for the period covering the date you choose.",
    noValidatedItems: "No item period was found in the verified data for this lookup date.",
    noFilteredItems: "No items match the current factual filter.",
    statusExact: "One exact record match",
    statusMultiple: "Multiple record matches",
    statusUnavailable: "No result in the verified dataset",
    showMoreItems: "Show more ({shown} of {total} shown)",
    showingAll: "All {total} shown.",
    tabDrugLookup: "Drug lookup",
    tabRiskTier: "Risk tier",
    tabGroupLabel: "Lookup mode",
    riskPanelTitle: "One question at a time",
    riskRemaining: "{count} unanswered",
    riskLdlLabel: "Current LDL-C (mg/dL)",
    riskLdlPlaceholder: "e.g. 145",
    riskLdlInvalid: "Enter a number between 0 and 1000.",
    riskLdlWhy: "LDL-C is not only compared against the payment threshold — LDL-C≧190mg/dL is itself one of the high-risk criteria, so high risk cannot be ruled out while it is blank.",
    riskEdit: "Change",
    riskReset: "Start over",
    riskNext: "Next",
    riskYes: "Yes",
    riskNo: "No",
    riskAnsweredYes: "Yes",
    riskAnsweredNo: "No",
    riskAnyOfHint: "Tick any that apply. Leaving them all unticked and pressing Next records none of them.",
    riskPrerequisiteQuestion: "Does the patient have the following?",
    riskUndeterminedTitle: "Not determined yet",
    riskUndeterminedBody: "On the answers so far it could be: {tiers}. {count} questions are unanswered, though answering some of them may well settle it — you will not be asked all of them.",
    riskUndeterminedWhy: "An unanswered question counts as unknown, never as no — reading it as no would under-rate the tier.",
    riskNeedLdl: "Fill in LDL-C above before a tier can be named.",
    riskTierEyebrow: "ASCVD risk tier",
    riskReasonCriterion: "Met: {text}",
    riskReasonWithPrerequisite: "Met: {prerequisite}, together with \u300c{text}\u300d",
    riskReasonFactorCount: "Met: {rule} ({count} present)",
    riskStatLdl: "Current LDL-C",
    riskStatThreshold: "Treatment threshold",
    riskStatPrimary: "Primary target",
    riskStatSecondary: "Secondary target (non-HDL-C)",
    riskStatBlank: "Not entered",
    riskStatNone: "Not stated",
    riskPrescriptionTitle: "Prescribing rule for this tier",
    riskPrescriptionNote: "Each step below is the announcement's own text, split on its own numbering. Nothing is reworded.",
    riskPrescriptionVerbatim: "Official text (unsplit)",
    riskPrescriptionNone: "The announcement states no prescribing rule for this row. The tool does not apply another tier's rule in its place.",
    riskProvenance: "Source: 2026-09-01 announcement, attachment 2 (payment-rule revision table) · {version}",
    riskSkipped: "These no longer change the result and were skipped: {reason}",
    riskSkippedTier: "the tier is already {tier}",
    riskNoDrugAdvice: "The tool does not classify statin intensity or pick an item for you.",
    riskAnswersLabel: "Answered",
    riskEmptyTitle: "Not started",
    riskEmptyBody: "Answer the announcement's criteria on the left. The right-hand column shows the resulting risk tier, its treatment threshold and targets, and the announcement's own prescribing rule.",
    riskItemsTitle: "Matching NHI items and prices",
    riskItemsNote: "Master items whose ingredient names {generic} and that carry a price on {date}.",
    riskItemsPartial: "The prescribing rule also names {classes}. The master holds no item of any of those, so what follows covers only the statin and ezetimibe part of it.",
    riskItemsExcluded: "A further {count} were left out: their payment price on that date is 0.00.",
    riskClassStatin: "Statins ({count})",
    riskClassEzetimibe: "Ezetimibe ({count})",
    riskGenericPrompt: "Pick an ingredient to list its items and prices.",
    riskGenericChip: "{name} ({count})",
    riskItemsPickGeneric: "No ingredient selected yet.",
    riskAdviceTitle: "Assessment advice for this tier",
    riskAdviceNote: "The announcement prints assessment advice per tier below the table. What follows is that text, split on its own numbering. Nothing is reworded.",
    riskAdviceNone: "The announcement's advice covers two groups only and states none for this row. The tool does not apply another tier's advice in its place.",
    riskSecondaryNoteLabel: "What the announcement says about the secondary target (verbatim)",
    riskCoverageTitle: "Coverage rules for ezetimibe",
    riskCoverageNote: "The same announcement also revised the coverage rules for ezetimibe and its combination products. What follows is the revised text, unreworded. The tool makes no coverage determination about any patient, and does not show the prior version alongside.",
    riskCoverageExceptionSummary: "The items the rule's \u201clisted below\u201d table names",
    riskCoverageExceptionNote: "The announcement's table lists {total} NHI codes. The {count} that carry a price on {date} follow.",
    riskCoverageUnresolved: "A further {count} carry no price in the master on that date and are not listed: {codes}",
    privacyText:
      "Do not enter names, medical record numbers, or any identifiable patient information. Clinical values are neither logged, stored, nor sent anywhere.",
    footerAttribution:
      "Source: National Health Insurance Administration, Ministry of Health and Welfare, NHI Drug Item Query File (data.gov.tw), used under the Open Government Data License, Version 1.0.",
    footerPrivacy:
      "This site has no accounts and collects no personal data; lookup content is neither logged nor stored.",
    footerCredit: "Planned, developed and produced by Josh Tsai, Universal Integrated Corp."
  })
});

export type UiMessageKey = keyof (typeof UI_COPY)["zh"];
export type UiReplacements = Readonly<Record<string, string>>;
export type Translator = (key: UiMessageKey, replacements?: UiReplacements) => string;
