/**
 * Every string the screen can show, in both interface languages.
 *
 * Kept out of App.tsx so that file stays about layout. Official warning and rule
 * text never appears here — that comes from the domain package verbatim.
 */
export const UI_COPY = Object.freeze({
  zh: Object.freeze({
    themeLightButton: "主題：明亮（切換至暗黑）",
    themeDarkButton: "主題：暗黑（切換至明亮）",
    languageControlLabel: "介面語言",
    languageChinese: "中文",
    languageEnglish: "English",
    drugLookupTab: "藥品查詢",
    ruleLookupTab: "規則逐字查詢",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "健保降血脂藥品查詢",
    appTagline: "查 2026-09-01 新制調整了哪些品項、價格多少,以及 2.6.1–2.6.3 給付規定改了什麼。價格全部取自健保署公開資料。",
    versionPill: "規則版本 民國115年9月1日生效 · 藥品主檔 2026-08-06 快照",
    disclaimer:
      "本工具非健保署系統,查詢結果不可作為申報依據,實際品項、價格與給付規定以健保署公告為準。不判斷任何病人是否符合給付,也不接受病人資料。",
    queryPanelTitle: "查詢條件",
    resultsPanelTitle: "查詢結果",
    resultsEmptyTitle: "等待查詢",
    resultsEmptyBody: "輸入健保代碼、中文品名、英文品名或成分,右側會列出品項、該日期適用的支付價,以及是否受 2026-09-01 公告影響。",
    ruleResultsEmptyTitle: "等待查詢",
    ruleResultsEmptyBody: "輸入章節代號或關鍵字,會列出條文中代碼在主檔的記錄、新舊制對照,以及官方逐字條文。",
    statMatched: "命中品項",
    statPriceChanged: "本次調價",
    statPriceUnchanged: "本次未調價",
    statAsOfDate: "查詢日期",
    statRuleUnits: "逐字單元",
    statRuleCodes: "條文代碼",
    statRuleSections: "章節",
    advancedTitle: "進階：指定資料集版本",
    showItemDetails: "展開完整欄位",
    hideItemDetails: "收合完整欄位",
    officialSourcesTitle: "官方轉錄警語與資料來源",
    expandOfficialSources: "展開官方轉錄警語與資料來源（目前已收合）",
    collapseOfficialSources: "收合官方轉錄警語與資料來源（目前已展開）",
    sourceMasterLabel: "藥品主檔",
    sourceAnnouncementLabel: "2026-09-01 公告異動明細",
    sourceRulesLabel: "給付規定 2.6.1–2.6.3（新制）",
    sourceRulesPriorLabel: "給付規定 2.6.1–2.6.3（舊制）",
    ruleTitle: "官方規則逐字查詢",
    ruleSubtitle: "以章節、單元編號或表名查找已驗證的逐字單元。",
    ruleSearchLabel: "規則搜尋",
    ruleSearchPlaceholder: "例如 2.6.1、2.6.1-002 或表一",
    ruleDateLabel: "規則查詢日期",
    datePlaceholder: "查詢日期 YYYY-MM-DD",
    ruleDatasetLabel: "規則資料集版本",
    datasetPlaceholder: "資料集版本",
    ruleSearchButton: "查詢規則原文",
    clausePath: "clausePath：{value}",
    rootClause: "（根層）",
    filterAll: "全部",
    filterPriceChanged: "本次調價",
    filterPriceUnchanged: "本次未調價",
    doseFilter: "劑量",
    doseFilterAll: "全部劑量（{count}）",
    doseFilterOption: "{label}（{count}）",
    doseUnspecified: "劑量未標示",
    doseNote:
      "劑量取自主檔的成分欄與英文品名兩者聯集。鹽類成分記載的是鹽重（如 atorvastatin calcium 10.85 mg），與標示含量（10 mg）並列，兩個都查得到；數值一律照主檔原樣，不換算、不四捨五入。",
    doseSelectedEmpty: "目前條件下沒有此劑量的品項。",
    announcementSourceTitle: "另一資料來源：2026-09-01 公告異動明細",
    announcementDatasetVersion: "資料集版本：{result.datasetVersion}",
    announcementNotFound: "此主檔代碼未列於 2026-09-01 公告資料集。",
    announcementChangedTitle: "2026-09-01 公告價格對照",
    priceComparison: "原支付價 {priceBefore} → 初核價格 {priceAfter}",
    priceBefore: "原支付價：{value}",
    priceAfter: "初核價格：{value}",
    effectiveDate: "生效日：{value}",
    announcementRuleSection: "給付規定章節：{value}",
    tableTwoMembership: "表二歸屬：{value}",
    trialNote: "三個月試用期註記：{value}",
    missingField: "本資料列未提供",
    fieldEnglishName: "英文品名：{value}",
    fieldNhiCode: "健保代碼：{value}",
    fieldIngredient: "成分及含量：{value}",
    fieldSpecification: "規格：{value}",
    fieldDosageForm: "劑型：{value}",
    fieldVendor: "藥商：{value}",
    fieldManufacturer: "製造廠：{value}",
    fieldAtc: "ATC：{value}",
    fieldCategory: "藥品分類：{value}",
    fieldClassificationGroup: "分類分組名稱：{value}",
    fieldSingleCompound: "單複方：{value}",
    applicablePriceTitle: "該查詢日期適用之支付價",
    validPeriod: "有效期間：{start} 至 {end}",
    masterSnapshotNotice:
      "主檔資料集版本 {version} 為 {snapshotDate} 時點快照；主檔最新價格期間為 {start} 至 {end}。上方公告價格對照另載該快照日之後、生效日 {effectiveDate} 的異動。",
    priceHistoryTitle: "價格沿革",
    expandPriceHistory: "展開價格沿革（{count} 筆，目前已收合）",
    collapsePriceHistory: "收合價格沿革（{count} 筆，目前已展開）",
    validPeriodHeader: "有效期間",
    paymentPriceHeader: "支付價",
    dateRange: "{start} 至 {end}",
    paymentPriceValue: "支付價：{value}",
    ruleSectionTitle: "給付規定章節",
    openRuleLabel: "開啟規則 {section} 的逐字條文",
    openRuleLink: "{section}（開啟逐字條文）",
    drugTitle: "藥品查詢",
    drugSubtitle: "以健保代碼、中文品名、英文品名或成分查找品項主檔。",
    drugSearchLabel: "藥品主檔搜尋",
    drugSearchPlaceholder: "輸入中文品名、健保代碼、英文品名或成分",
    drugDateLabel: "藥品主檔查詢日期",
    drugDatasetLabel: "藥品主檔資料集版本",
    drugSearchButton: "查詢藥品主檔",
    sectionFilter: "章節篩選：{section}",
    clearSectionFilter: "清除章節篩選",
    resultFilter: "結果篩選",
    officialWarningTitle: "官方轉錄警語",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "查詢結果：{status}",
    sectionItemsTitle: "章節品項：{section}",
    resultMetadata: "資料集版本：{version} · 查詢日期：{date}",
    multipleReviewDrug:
      "目前畫面列出全部 {count} 筆符合目前條件的候選；工具不會代為選取任何品項或期別。",
    manualReviewDrug: "此結果需要人工確認；系統不會自動選取品項或替代期別。",
    excludedZeroPrice: "另有 {count} 筆符合查詢的品項，因該查詢日期之支付價為 0.00 未列出。",
    asOfDatePresetToday: "今天（{value}）",
    asOfDatePresetAnnouncement: "新制生效日（{value}）",
    asOfDatePickerHint: "點日期欄位可開啟日曆選擇其他日期。價格依所選日期適用之期別顯示。",
    noValidatedItems: "該查詢日期沒有已驗證資料所涵蓋的品項期別。",
    noFilteredItems: "此結果篩選目前沒有品項。",
    ruleResultMetadata: "資料集版本：{version} · 生效日：{date}",
    ruleSourceTag: "來源標記：{value}",
    manualReviewRule: "此結果需要人工確認；請比對健保署公告原文。",
    viewSectionItems: "查看本章節品項（{section}）",
    noRuleUnits: "此查詢未取得已驗證的逐字單元。",
    officialRuleTextTitle: "官方條文",
    ruleTextSectionTitle: "章節 {section}（{count} 個單元）",
    expandRuleTextSection: "展開章節 {section}（目前已收合）",
    collapseRuleTextSection: "收合章節 {section}（目前已展開）",
    expandAllRuleUnits: "展開章節 {section} 的全部 {count} 個單元",
    collapseAllRuleUnits: "收合章節 {section} 的全部 {count} 個單元",
    ruleUnitType: "類型：{value}",
    ruleUnitTableLabel: "表別：{value}",
    expandRuleUnit: "展開單元 {unitId}（目前已收合）",
    collapseRuleUnit: "收合單元 {unitId}（目前已展開）",
    ruleDiffTitle: "新舊條文逐段對照",
    ruleDiffPriorColumn: "舊制（適用至 {effectiveTo}）",
    ruleDiffCurrentColumn: "新制（{effectiveFrom} 生效）",
    ruleDiffKindUnchanged: "未變更",
    ruleDiffKindRemoved: "刪除",
    ruleDiffKindAdded: "新增",
    ruleDiffKindReplaced: "改寫",
    ruleDiffStats: "舊制共 {priorTokens} 個字元單位，其中 {unchanged} 個在新制中保留；新制另有 {added} 個為新增。",
    ruleDiffMethod:
      "本表以最長共同子序列逐字元對齊兩版條文，並抑制過短的偶然相符。對齊為演算法結果，不是法律判讀：同一列並排的刪除與新增，代表兩者在比對結果中相鄰，不代表主管機關是把左邊改寫成右邊。比對時忽略換行（兩份來源的換行皆為排版產物），本表另於句號後重新斷行以利閱讀，並將英文大小寫與全形半形標點視為相同，因此標示「未變更」的兩欄仍可能有大小寫或標點差異，兩欄並列即可看出。條文原文未經修改，另存於上方舊制全文與下方官方條文。",
    ruleComparisonTermsTitle: "量化條件摘要",
    ruleComparisonTitle: "新舊制對照（{section}）",
    expandRuleComparison: "展開新舊制對照（{section}，目前已收合）",
    collapseRuleComparison: "收合新舊制對照（{section}，目前已展開）",
    ruleComparisonPriorMeta: "舊制：最後修訂 {revision}；修訂沿革 {history}",
    ruleComparisonPriorDataset: "舊制資料集：{version}（適用至 {effectiveTo}）",
    ruleComparisonCurrentDataset: "新制資料集：{version}（{effectiveFrom} 生效，{count} 個單元）",
    ruleComparisonSourcePdf: "舊制來源 PDF：{name}（{bytes} bytes，SHA-256 {hash}）",
    ruleComparisonMethod:
      "以下比對僅就機械擷取之量化條件（療程與追蹤期間、血脂數值門檻）列出兩制差異，未做逐句比對；文字敘述之增刪不在此列，仍須自行閱讀兩制全文。",
    ruleComparisonRemoved: "僅見於舊制（{count}）",
    ruleComparisonAdded: "僅見於新制（{count}）",
    ruleComparisonRetained: "兩制皆有（{count}）",
    ruleComparisonNone: "本節未擷取到可比對之量化條件。",
    ruleComparisonPriorTextTitle: "舊制條文全文",
    expandPriorRuleText: "展開舊制條文全文（目前已收合）",
    collapsePriorRuleText: "收合舊制條文全文（目前已展開）",
    ruleDiffExcludedListing:
      "本對照未納入條文 {unitId} 的藥品清單表（{characters} 字、{codes} 個健保代碼）。該表為新制新增，舊制條文中沒有對應內容，納入比對只會成為一整格「改寫」，看不出給付規定改了什麼。清單的官方全文未經更動，在下方「官方規則逐字條文」的 {unitId} 內完整呈現；{codes} 個代碼對應的品名、成分、劑型則在上方「條文中出現之代碼在藥品主檔的記錄」逐筆列出。",
    ruleDrugMasterTitle: "條文中出現之代碼在藥品主檔的記錄（{count} 筆）",
    ruleDrugMasterNoCodes: "本次結果之條文中未出現符合代碼格式之字串。",
    expandRuleDrugMaster: "展開主檔辨識記錄（{count} 筆，目前已收合）",
    collapseRuleDrugMaster: "收合主檔辨識記錄（{count} 筆，目前已展開）",
    ruleDrugMasterDatasetVersion: "藥品主檔資料集版本：{version}",
    ruleDrugMasterMissing: "主檔查無此代碼；未以條文文字填補。",
    fieldMasterChineseName: "主檔中文品名：{value}",
    fieldMasterEnglishName: "主檔英文品名：{value}",
    fieldMasterIngredient: "主檔成分：{value}",
    fieldMasterSpecification: "主檔規格量與單位：{value}",
    fieldMasterDosageForm: "主檔劑型：{value}",
    statusExact: "單筆精確命中",
    statusMultiple: "多筆命中",
    statusUnavailable: "未在已驗證資料集取得結果",
    privacyTitle: "此工具不接受病人資料",
    privacyText: "請勿輸入姓名、病歷號、檢驗值、診斷或任何可識別病人資訊。",
    footerAttribution:
      "資料來源:衛生福利部中央健康保險署『健保用藥品項查詢項目檔』(政府資料開放平臺),依政府資料開放授權條款第1版利用",
    footerPrivacy: "本站不設帳號、不蒐集任何個人資料;查詢內容不記錄、不儲存。"
  }),
  en: Object.freeze({
    themeLightButton: "Theme: Light (switch to Dark)",
    themeDarkButton: "Theme: Dark (switch to Light)",
    languageControlLabel: "Interface language",
    languageChinese: "中文",
    languageEnglish: "English",
    drugLookupTab: "Drug lookup",
    ruleLookupTab: "Verbatim rule lookup",
    appEyebrow: "NHI LIPID-LOWERING DRUG LOOKUP",
    appTitle: "NHI Lipid-Lowering Drug Lookup",
    appTagline:
      "Which items the 2026-09-01 announcement repriced, what each costs, and what changed in coverage rules 2.6.1–2.6.3. Every price comes from NHI's own published data.",
    versionPill: "Rules effective 2026-09-01 · Drug master snapshot 2026-08-06",
    disclaimer:
      "This is not an NHI system. Results cannot be used as a basis for claims; the NHI's own announcements govern. The tool makes no coverage determination for any patient and accepts no patient data.",
    queryPanelTitle: "Query",
    resultsPanelTitle: "Results",
    resultsEmptyTitle: "Waiting for a query",
    resultsEmptyBody:
      "Enter an NHI code, Chinese or English drug name, or ingredient. Results list each item, the payment price for the date you chose, and whether the 2026-09-01 announcement affected it.",
    ruleResultsEmptyTitle: "Waiting for a query",
    ruleResultsEmptyBody:
      "Enter a section number or keyword. Results show the drug-master records for codes in the rule text, the prior/current comparison, and the official verbatim text.",
    statMatched: "Items matched",
    statPriceChanged: "Price changed",
    statPriceUnchanged: "Price not changed",
    statAsOfDate: "Lookup date",
    statRuleUnits: "Verbatim units",
    statRuleCodes: "Codes in text",
    statRuleSections: "Sections",
    advancedTitle: "Advanced: pin a dataset version",
    showItemDetails: "Show all fields",
    hideItemDetails: "Hide all fields",
    officialSourcesTitle: "Official transcription warnings and sources",
    expandOfficialSources: "Show official transcription warnings and sources (currently hidden)",
    collapseOfficialSources: "Hide official transcription warnings and sources (currently shown)",
    sourceMasterLabel: "Drug master",
    sourceAnnouncementLabel: "2026-09-01 announcement change details",
    sourceRulesLabel: "Coverage rules 2.6.1–2.6.3 (current)",
    sourceRulesPriorLabel: "Coverage rules 2.6.1–2.6.3 (prior)",
    ruleTitle: "Official verbatim rule lookup",
    ruleSubtitle: "Find verified verbatim units by section, unit number, or table name.",
    ruleSearchLabel: "Rule search",
    ruleSearchPlaceholder: "For example, 2.6.1, 2.6.1-002, or 表一",
    ruleDateLabel: "Rule lookup date",
    datePlaceholder: "Lookup date YYYY-MM-DD",
    ruleDatasetLabel: "Rule dataset version",
    datasetPlaceholder: "Dataset version",
    ruleSearchButton: "Search rule text",
    clausePath: "Clause path: {value}",
    rootClause: "(root)",
    filterAll: "All",
    filterPriceChanged: "Price changed",
    filterPriceUnchanged: "Price not changed",
    doseFilter: "Dose",
    doseFilterAll: "All doses ({count})",
    doseFilterOption: "{label} ({count})",
    doseUnspecified: "Dose not stated",
    doseNote:
      "Doses are read from the master's ingredient field and English drug name, unioned. Salt forms state the salt weight (e.g. atorvastatin calcium 10.85 mg) alongside the label strength (10 mg), and both can be searched; values are shown exactly as the master states them, never converted or rounded.",
    doseSelectedEmpty: "No item carries this dose under the current filters.",
    announcementSourceTitle: "Separate source: 2026-09-01 announcement change details",
    announcementDatasetVersion: "Dataset version: {result.datasetVersion}",
    announcementNotFound: "This master code is not listed in the 2026-09-01 announcement dataset.",
    announcementChangedTitle: "2026-09-01 announcement price comparison",
    priceComparison:
      "Previous payment price {priceBefore} → Initial review price {priceAfter}",
    priceBefore: "Previous payment price: {value}",
    priceAfter: "Initial review price: {value}",
    effectiveDate: "Effective date: {value}",
    announcementRuleSection: "Rule section: {value}",
    tableTwoMembership: "Table 2 classification: {value}",
    trialNote: "3-month trial note: {value}",
    missingField: "Not provided in this source row",
    fieldEnglishName: "English product name: {value}",
    fieldNhiCode: "NHI code: {value}",
    fieldIngredient: "Ingredient and strength: {value}",
    fieldSpecification: "Specification: {value}",
    fieldDosageForm: "Dosage form: {value}",
    fieldVendor: "Vendor: {value}",
    fieldManufacturer: "Manufacturer: {value}",
    fieldAtc: "ATC: {value}",
    fieldCategory: "Drug category: {value}",
    fieldClassificationGroup: "Classification group: {value}",
    fieldSingleCompound: "Single or combination product: {value}",
    applicablePriceTitle: "Payment price for the lookup date",
    validPeriod: "Effective period: {start} to {end}",
    masterSnapshotNotice:
      "Master dataset version {version} is a snapshot dated {snapshotDate}. Its latest price period runs from {start} to {end}. The announcement price comparison above separately records a change after that snapshot date, effective {effectiveDate}.",
    priceHistoryTitle: "Price history",
    expandPriceHistory: "Expand price history ({count} entries, currently collapsed)",
    collapsePriceHistory: "Collapse price history ({count} entries, currently expanded)",
    validPeriodHeader: "Effective period",
    paymentPriceHeader: "Payment price",
    dateRange: "{start} to {end}",
    paymentPriceValue: "Payment price: {value}",
    ruleSectionTitle: "Rule section",
    openRuleLabel: "Open the verbatim text for rule {section}",
    openRuleLink: "{section} (open verbatim rule text)",
    drugTitle: "Drug lookup",
    drugSubtitle: "Find master items by NHI code, Chinese name, English name, or ingredient.",
    drugSearchLabel: "Drug master search",
    drugSearchPlaceholder: "Enter a Chinese name, NHI code, English name, or ingredient",
    drugDateLabel: "Drug master lookup date",
    drugDatasetLabel: "Drug master dataset version",
    drugSearchButton: "Search drug master",
    sectionFilter: "Section filter: {section}",
    clearSectionFilter: "Clear section filter",
    resultFilter: "Result filters",
    officialWarningTitle: "Official transcription warning",
    originalLanguageNote:
      "Official warnings and rule text appear in their original Chinese wording.",
    resultTitle: "Lookup result: {status}",
    sectionItemsTitle: "Section items: {section}",
    resultMetadata: "Dataset version: {version} · Lookup date: {date}",
    multipleReviewDrug:
      "The current view lists all {count} candidates matching the current filters; the tool does not select any item or price period for you.",
    manualReviewDrug: "This result requires manual review; no item or price period is selected automatically.",
    excludedZeroPrice:
      "A further {count} item(s) matched the query but are not listed, because their payment price for that date is 0.00.",
    asOfDatePresetToday: "Today ({value})",
    asOfDatePresetAnnouncement: "Announcement effective date ({value})",
    asOfDatePickerHint:
      "Tap the date field to open a calendar and pick another date. Prices are shown for the period covering the date you choose.",
    noValidatedItems: "No item period was found in the verified data for this lookup date.",
    noFilteredItems: "No items match the current factual filter.",
    ruleResultMetadata: "Dataset version: {version} · Effective date: {date}",
    ruleSourceTag: "Source tag: {value}",
    manualReviewRule: "This result requires manual review; compare it with the original NHI announcement.",
    viewSectionItems: "View items in this section ({section})",
    noRuleUnits: "No verified verbatim unit was found for this query.",
    officialRuleTextTitle: "Official rule text",
    ruleTextSectionTitle: "Section {section} ({count} units)",
    expandRuleTextSection: "Expand section {section} (currently collapsed)",
    collapseRuleTextSection: "Collapse section {section} (currently expanded)",
    expandAllRuleUnits: "Expand all {count} units in section {section}",
    collapseAllRuleUnits: "Collapse all {count} units in section {section}",
    ruleUnitType: "Type: {value}",
    ruleUnitTableLabel: "Table label: {value}",
    expandRuleUnit: "Expand unit {unitId} (currently collapsed)",
    collapseRuleUnit: "Collapse unit {unitId} (currently expanded)",
    ruleDiffTitle: "Prior and current text, segment by segment",
    ruleDiffPriorColumn: "Prior (in force until {effectiveTo})",
    ruleDiffCurrentColumn: "Current (effective {effectiveFrom})",
    ruleDiffKindUnchanged: "Unchanged",
    ruleDiffKindRemoved: "Removed",
    ruleDiffKindAdded: "Added",
    ruleDiffKindReplaced: "Rewritten",
    ruleDiffStats:
      "The prior version has {priorTokens} character units, {unchanged} of which survive in the current version; the current version adds a further {added}.",
    ruleDiffMethod:
      "This table aligns the two versions with a longest-common-subsequence over characters and suppresses coincidental short matches. The alignment is an algorithm result, not a legal reading: a removal and an addition on the same row are adjacent in the comparison, which does not mean the regulator rewrote the left into the right. Line breaks are ignored (they are layout artifacts in both sources) and this table re-wraps after each full stop for readability and letter case and full/half-width punctuation are treated as equal, so a row marked unchanged may still differ in case or punctuation — both columns are shown so that difference stays visible. Neither official text is modified; both remain above and below in full.",
    ruleComparisonTermsTitle: "Quantitative terms at a glance",
    ruleComparisonTitle: "Prior version compared with current ({section})",
    expandRuleComparison: "Expand prior/current comparison ({section}, currently collapsed)",
    collapseRuleComparison: "Collapse prior/current comparison ({section}, currently expanded)",
    ruleComparisonPriorMeta: "Prior version: last revised {revision}; revision history {history}",
    ruleComparisonPriorDataset: "Prior dataset: {version} (in force until {effectiveTo})",
    ruleComparisonCurrentDataset:
      "Current dataset: {version} (effective {effectiveFrom}, {count} units)",
    ruleComparisonSourcePdf: "Prior source PDF: {name} ({bytes} bytes, SHA-256 {hash})",
    ruleComparisonMethod:
      "This comparison lists only mechanically extracted quantitative terms (treatment and follow-up intervals, lipid value thresholds) that differ between the two versions. Sentences are not aligned and wording changes are not listed, so both full texts still need to be read.",
    ruleComparisonRemoved: "Only in the prior version ({count})",
    ruleComparisonAdded: "Only in the current version ({count})",
    ruleComparisonRetained: "In both versions ({count})",
    ruleComparisonNone: "No comparable quantitative term was extracted for this section.",
    ruleComparisonPriorTextTitle: "Prior version, full text",
    expandPriorRuleText: "Expand prior version full text (currently collapsed)",
    collapsePriorRuleText: "Collapse prior version full text (currently expanded)",
    ruleDiffExcludedListing:
      "This comparison leaves out the drug listing in unit {unitId} ({characters} characters, {codes} NHI codes). The listing is new; the prior text has no counterpart, so comparing it can only produce one undifferentiated “rewritten” cell that says nothing about how the coverage conditions changed. The official text of the listing is unaltered and shown in full under {unitId} in the verbatim rule text below, and the {codes} codes are resolved to names, ingredients and dosage forms in the drug-master records above.",
    ruleDrugMasterTitle: "Drug-master records for codes appearing in the rule text ({count} entries)",
    ruleDrugMasterNoCodes:
      "No strings matching the code format appear in the rule text for this result.",
    expandRuleDrugMaster:
      "Expand drug-master identification records ({count} entries, currently collapsed)",
    collapseRuleDrugMaster:
      "Collapse drug-master identification records ({count} entries, currently expanded)",
    ruleDrugMasterDatasetVersion: "Drug master dataset version: {version}",
    ruleDrugMasterMissing:
      "No record was found for this code in the drug master; rule text was not used to fill it.",
    fieldMasterChineseName: "Master Chinese product name: {value}",
    fieldMasterEnglishName: "Master English product name: {value}",
    fieldMasterIngredient: "Master ingredient: {value}",
    fieldMasterSpecification: "Master specification amount and unit: {value}",
    fieldMasterDosageForm: "Master dosage form: {value}",
    statusExact: "One exact record match",
    statusMultiple: "Multiple record matches",
    statusUnavailable: "No result in the verified dataset",
    privacyTitle: "This tool does not accept patient data",
    privacyText:
      "Do not enter names, medical record numbers, test results, diagnoses, or any identifiable patient information.",
    footerAttribution:
      "Source: National Health Insurance Administration, Ministry of Health and Welfare, NHI Drug Item Query File (data.gov.tw), used under the Open Government Data License, Version 1.0.",
    footerPrivacy:
      "This site has no accounts and collects no personal data; lookup content is neither logged nor stored."
  })
});

export type UiMessageKey = keyof (typeof UI_COPY)["zh"];
export type UiReplacements = Readonly<Record<string, string>>;
export type Translator = (key: UiMessageKey, replacements?: UiReplacements) => string;
